"""Changelog pipeline: legacy full rewrite or per-deploy tagged sections.

Run from vault/repo root. Requires git-cliff binary (e.g. brew install git-cliff) when
run_cliff is True. Polish step uses the same backend as triage (TOCIFY_BACKEND: openai,
gemini, or cursor). Skip when skip_polish is True or no backend is available (no API key
or, for cursor, `agent` not on PATH).
"""

from __future__ import annotations

import os
import re
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path

from tocify.integrations import get_run_completion
from tocify.runner.prompt_templates import load_prompt_template

# Lines containing any of these (substring, case-insensitive) are dropped.
MINOR_PHRASES = [
    "workflow debug",
    "workflow improvements",
    "weekly flow now works",
    "weekly generation",
    "weekly action just install",
    "monthly action just install",
    "derive email subject dates",
    "derive email dates from brief",
    "install playwright",
    "cursor cli works",
    "quartz build from root",
    "check for dead code",
    "tocify refactor",
    "import tocify",
    "obsidian vault settings",
    "try obsidian-git",
    "archive ready",
    "about files",
    "empty headers",
    "ignore logs and duplicates",
    "rss feeds",
    "manual gardening",
    "map html",
    "feeds folder no file count",
    "hide folder count for feeds",
    "fixed downloads and briefs",
    "colophone",
    "colophon footer url",
    "no latex and broken html",
    "lessen load of articles",
    "homepage update, readme",
    "2026-01",
    "2025 with companies and news",
]

MIN_CONTENT_LENGTH = 14
_DATE_PREFIX = re.compile(r"^- (\d{4}-\d{2}-\d{2}) — ")
_SECTION_HEADING = re.compile(r"^## ", re.MULTILINE)
_FOOTER_MARKER = "\n---\n*Generated by [git-cliff](https://git-cliff.org).*"

_CONSISTENCY_REPLACEMENTS: list[tuple[str, str]] = [
    ("explicitely", "explicitly"),
    ("left aligh ", "left align "),
    ("refresh briefs. to-do- fix hn fetch range", "refresh briefs; to-do: fix hn fetch range"),
    ("Darkmode/", "DarkMode/"),
    ("repairing graph", "repair graph"),
]


@dataclass(frozen=True)
class ChangelogDocument:
    """Structured changelog document split into header, body, and footer."""

    header: str
    body: str
    footer: str


def _load_dotenv(repo_root: Path) -> None:
    """Load .env from repo root into os.environ so CURSOR_API_KEY is set if present."""
    env_file = repo_root / ".env"
    if not env_file.is_file():
        return
    for line in env_file.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, _, value = line.partition("=")
            key = key.strip()
            if key and key not in os.environ:
                value = value.strip().strip("'\"").strip()
                os.environ[key] = value


def find_repo_root(start: Path) -> Path | None:
    """Return first directory containing .git above or at start, or None."""
    root = start.resolve()
    while True:
        if (root / ".git").exists():
            return root
        parent = root.parent
        if parent == root:
            return None
        root = parent


def _dedupe_changelog(path: Path) -> None:
    """Deduplicate list items (- ...) within each ## section."""
    text = path.read_text()
    lines = text.splitlines(keepends=True)
    out: list[str] = []
    in_section = False
    seen: set[str] = set()
    section_buffer: list[str] = []

    def flush_section() -> None:
        nonlocal section_buffer, seen
        for line in section_buffer:
            stripped = line.strip()
            if stripped.startswith("- "):
                if stripped not in seen:
                    seen.add(stripped)
                    out.append(line)
            else:
                out.append(line)
        section_buffer = []

    for line in lines:
        if line.startswith("## "):
            flush_section()
            seen.clear()
            in_section = True
            out.append(line)
            continue
        if in_section:
            section_buffer.append(line)
        else:
            out.append(line)
    flush_section()
    path.write_text("".join(out))


def _normalize_subject(subject: str) -> str:
    """Strip conventional prefix and normalize for matching."""
    s = re.sub(
        r"^(feat|fix|chg|doc|content|new)(\([^)]+\))?:\s*",
        "",
        subject,
        flags=re.IGNORECASE,
    )
    return s.strip().lower()


def _normalize_changelog_content(content: str) -> str:
    """Remove scope prefix and normalize for lookup."""
    s = re.sub(r"\*\*[^*]+\*\* — ", "", content).strip().lower()
    return s


def _build_message_to_date(repo_root: Path) -> dict[str, str]:
    """Run git log --reverse, return map normalized_message -> YYYY-MM-DD (oldest)."""
    result = subprocess.run(
        ["git", "log", "--all", "--reverse", "--format=%ad\t%s", "--date=short"],
        capture_output=True,
        text=True,
        cwd=repo_root,
    )
    if result.returncode != 0:
        return {}
    message_to_date: dict[str, str] = {}
    for line in result.stdout.splitlines():
        line = line.strip()
        if "\t" not in line:
            continue
        date, subject = line.split("\t", 1)
        key = _normalize_subject(subject)
        if key and key not in message_to_date:
            message_to_date[key] = date
    return message_to_date


def _add_changelog_dates(path: Path, repo_root: Path) -> None:
    """Prepend YYYY-MM-DD from git log to each list line."""
    message_to_date = _build_message_to_date(repo_root)
    lines = path.read_text().splitlines(keepends=True)
    out: list[str] = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("- "):
            content = stripped[2:].strip()
            key = _normalize_changelog_content(content)
            date = message_to_date.get(key)
            if not date and " — " in content:
                key2 = content.split(" — ", 1)[-1].strip().lower()
                date = message_to_date.get(key2)
            if not date:
                key3 = content.split("—")[-1].strip().lower()
                date = message_to_date.get(key3)
            if date:
                out.append(f"- {date} — {content}\n")
            else:
                out.append(line)
        else:
            out.append(line)
    path.write_text("".join(out))


def _strip_date_prefix(stripped: str) -> tuple[str | None, str]:
    """If line has date prefix, return (date, rest); else (None, stripped)."""
    m = _DATE_PREFIX.match(stripped)
    if m:
        return m.group(1), stripped[m.end() :]
    return None, stripped


def _has_scope(line: str) -> bool:
    """True if list item has scope e.g. '- **quartz** — ...' (maybe with date prefix)."""
    stripped = line.strip()
    if not stripped.startswith("- "):
        return False
    date, rest = _strip_date_prefix(stripped)
    logical = f"- {rest}" if date is not None else stripped
    return bool(re.match(r"^- \*\*[^*]+\*\* —", logical))


def _is_minor(line: str) -> bool:
    """True if line should be dropped as minor/tooling."""
    stripped = line.strip()
    if not stripped.startswith("- "):
        return False
    _, rest = _strip_date_prefix(stripped)
    content = (rest if rest else stripped[2:]).strip().lower()
    if len(content) < MIN_CONTENT_LENGTH:
        return True
    for phrase in MINOR_PHRASES:
        if phrase.lower() in content:
            return True
    return False


def _keep_line(line: str) -> bool:
    """True if this list line should be kept."""
    stripped = line.strip()
    if not stripped.startswith("- "):
        return True
    date, rest = _strip_date_prefix(stripped)
    logical = f"- {rest}" if date is not None else stripped
    if _has_scope(logical):
        return True
    if _is_minor(logical):
        return False
    return True


def _normalize_quartz(line: str) -> str:
    """Make 'quartz' consistently bold in list lines (preserve date prefix if present)."""
    stripped = line.strip()
    if not stripped.startswith("- "):
        return line
    date, rest = _strip_date_prefix(stripped)
    logical = f"- {rest}" if date is not None else stripped
    normalized = re.sub(
        r"(?<!\*)\bquartz\b(?!\*)",
        "**quartz**",
        logical,
        flags=re.IGNORECASE,
    )
    if date:
        normalized = f"- {date} — {normalized[2:]}"
    if line.endswith("\n"):
        normalized = normalized + "\n"
    return normalized


def _filter_changelog(path: Path) -> None:
    """Keep only important entries; normalize **quartz**."""
    lines = path.read_text().splitlines(keepends=True)
    out: list[str] = []
    for line in lines:
        if _keep_line(line):
            out.append(_normalize_quartz(line))
    path.write_text("".join(out))


def _extract_body(response_text: str) -> str | None:
    """Extract changelog body from agent stdout: from opening --- to end.

    Handles leading prose, code fences, and relaxed frontmatter (--- with title: in next lines).
    Returns None if no body found.
    """
    stripped = response_text.strip()
    if stripped.startswith("```"):
        match = re.match(
            r"^```(?:markdown|md)?\s*\n(.*)(?:\n```\s*$)?", stripped, re.DOTALL
        )
        if match:
            stripped = match.group(1).strip()
    lines = stripped.splitlines()
    lookahead = 10
    for i, line in enumerate(lines):
        if line.strip() != "---":
            continue
        chunk = (
            "\n".join(lines[i : i + lookahead])
            if i + lookahead <= len(lines)
            else "\n".join(lines[i:])
        )
        if "title:" in chunk:
            return "\n".join(lines[i:]).rstrip()
    if stripped.startswith("---") and "title:" in stripped[:500]:
        return stripped.rstrip()
    match = re.search(r"\n---\s*\n[\s\S]*?title:", stripped)
    if match:
        start = match.start() + 1
        return stripped[start:].rstrip()
    return None


def _apply_fallback_fixes(content: str) -> str:
    """Apply known typo/wording fixes when agent did not return the full document."""
    result = content
    for old, new in _CONSISTENCY_REPLACEMENTS:
        result = result.replace(old, new)
    return result


def _run_polish(
    changelog_path: Path,
    repo_root: Path,
    prompt_path: Path | None,
) -> None:
    """Run backend (same as triage) to polish changelog; extract body or apply fallback fixes."""
    polished = _polish_changelog_text(changelog_path.read_text(), repo_root, prompt_path)
    changelog_path.write_text(polished)


def _polish_changelog_text(
    content: str,
    repo_root: Path,
    prompt_path: Path | None,
) -> str:
    """Return polished changelog markdown, falling back to local replacements."""
    _load_dotenv(repo_root)
    run_fn = get_run_completion()
    if run_fn is None:
        print("changelog: skip polish (no backend available; set TOCIFY_BACKEND and API key or Cursor CLI)")
        return content if content.endswith("\n") else content + "\n"
    config_prompt_path = repo_root / "config" / "changelog_consistency_prompt.md"
    path = prompt_path if prompt_path is not None else (
        config_prompt_path if config_prompt_path.is_file() else None
    )
    instructions = load_prompt_template("changelog_consistency_prompt.md", path)
    prompt = f"{instructions}\n\n---\n\n{content}"
    try:
        response_text = run_fn(prompt)
    except FileNotFoundError:
        raise SystemExit(
            "changelog: 'agent' not on PATH. Install Cursor CLI, then export PATH=\"$HOME/.cursor/bin:$PATH\""
        ) from None
    except subprocess.TimeoutExpired as e:
        raise SystemExit(f"changelog: backend timed out (>{e.timeout}s)") from None
    except RuntimeError as e:
        raise SystemExit(f"changelog: backend error: {e}") from e
    body = _extract_body(response_text)
    if body is None:
        debug_path = repo_root / "changelog_agent_last_response.txt"
        try:
            debug_path.write_text(response_text, encoding="utf-8")
        except OSError:
            pass
        body = _apply_fallback_fixes(content)
        print(
            "changelog: applied fallback consistency fixes (agent returned summary, not full doc)"
        )
    else:
        print("changelog: polished with backend")
    return body if body.endswith("\n") else body + "\n"


def _run_git_cliff(
    repo_root: Path,
    cliff_path: Path,
    *,
    revision_range: str | None = None,
    strip_parts: tuple[str, ...] = (),
) -> str:
    """Run git-cliff and return the generated markdown."""
    with tempfile.NamedTemporaryFile(suffix=".md", delete=False) as tmp:
        output_path = Path(tmp.name)
    try:
        command = ["git-cliff", "-c", str(cliff_path), "-o", str(output_path)]
        for part in strip_parts:
            command.extend(["-s", part])
        if revision_range:
            command.append(revision_range)
        subprocess.run(command, cwd=repo_root, check=True)
        return output_path.read_text(encoding="utf-8")
    finally:
        output_path.unlink(missing_ok=True)


def _split_changelog_document(content: str) -> ChangelogDocument:
    """Split a git-cliff markdown document into header, body, and footer."""
    footer_index = content.rfind(_FOOTER_MARKER)
    if footer_index == -1:
        raise ValueError("Changelog footer marker not found")
    footer = content[footer_index + 1 :].strip()
    before_footer = content[:footer_index].rstrip()
    section_match = _SECTION_HEADING.search(before_footer)
    if section_match is None:
        raise ValueError("Changelog body heading not found")
    header = before_footer[: section_match.start()].strip()
    body = before_footer[section_match.start() :].strip()
    return ChangelogDocument(
        header=header + "\n\n",
        body=body + "\n",
        footer=footer + "\n",
    )


def _compose_changelog_document(document: ChangelogDocument) -> str:
    """Compose a changelog document with normalized spacing."""
    return (
        document.header.rstrip()
        + "\n\n"
        + document.body.strip()
        + "\n\n"
        + document.footer.strip()
        + "\n"
    )


def _postprocess_generated_body(body: str, repo_root: Path) -> str:
    """Run dedupe/date/filter transforms against generated changelog body."""
    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".md",
        delete=False,
        encoding="utf-8",
    ) as tmp:
        tmp.write(body if body.endswith("\n") else body + "\n")
        path = Path(tmp.name)
    try:
        _dedupe_changelog(path)
        _add_changelog_dates(path, repo_root)
        _filter_changelog(path)
        return path.read_text(encoding="utf-8").strip() + "\n"
    finally:
        path.unlink(missing_ok=True)


def _demote_release_headings(body: str) -> str:
    """Convert git-cliff's section headings into nested headings under a release tag."""
    return re.sub(r"^## ", "### ", body.strip(), flags=re.MULTILINE)


def _build_release_section(release_label: str, body: str) -> str:
    """Wrap processed git-cliff body into one tagged release section."""
    normalized_body = _demote_release_headings(body).strip()
    if not normalized_body:
        return ""
    return f"## {release_label}\n\n{normalized_body}\n"


def _polish_release_section(
    section: str,
    repo_root: Path,
    prompt_path: Path | None,
    document_template: ChangelogDocument,
) -> str:
    """Polish only the new release section by wrapping it in a temporary full document."""
    wrapped = _compose_changelog_document(
        ChangelogDocument(
            header=document_template.header,
            body=section,
            footer=document_template.footer,
        )
    )
    polished = _polish_changelog_text(wrapped, repo_root, prompt_path)
    return _split_changelog_document(polished).body


def _prepare_release_section(
    *,
    release_label: str,
    repo_root: Path,
    cliff_path: Path,
    prompt_path: Path | None,
    skip_polish: bool,
    document_template: ChangelogDocument,
    revision_range: str | None = None,
) -> str:
    """Generate, post-process, and optionally polish one tagged release section."""
    generated_body = _run_git_cliff(
        repo_root,
        cliff_path,
        revision_range=revision_range,
        strip_parts=("all",),
    )
    processed_body = _postprocess_generated_body(generated_body, repo_root)
    section = _build_release_section(release_label, processed_body)
    if not section:
        return ""
    if skip_polish:
        return section if section.endswith("\n") else section + "\n"
    polished_section = _polish_release_section(
        section,
        repo_root,
        prompt_path,
        document_template,
    )
    return polished_section if polished_section.endswith("\n") else polished_section + "\n"


def _write_migrated_changelog(
    changelog_path: Path,
    repo_root: Path,
    cliff_path: Path,
    release_label: str,
    *,
    prompt_path: Path | None,
    skip_polish: bool,
) -> None:
    """Build a fresh per-tag changelog document from history."""
    generated = _run_git_cliff(repo_root, cliff_path)
    template = _split_changelog_document(generated)
    section = _prepare_release_section(
        release_label=release_label,
        repo_root=repo_root,
        cliff_path=cliff_path,
        prompt_path=prompt_path,
        skip_polish=skip_polish,
        document_template=template,
    )
    document = _compose_changelog_document(
        ChangelogDocument(
            header=template.header,
            body=section,
            footer=template.footer,
        )
    )
    changelog_path.parent.mkdir(parents=True, exist_ok=True)
    changelog_path.write_text(document, encoding="utf-8")


def _insert_release_section(
    changelog_path: Path,
    section: str,
    *,
    prepend: bool,
) -> None:
    """Insert a new release section into an existing per-tag changelog."""
    if not section.strip():
        return
    existing = _split_changelog_document(changelog_path.read_text(encoding="utf-8"))
    existing_body = existing.body.strip()
    new_body = (
        f"{section.strip()}\n\n{existing_body}\n"
        if prepend and existing_body
        else section.strip() + "\n"
        if prepend
        else f"{existing_body}\n\n{section.strip()}\n"
        if existing_body
        else section.strip() + "\n"
    )
    changelog_path.write_text(
        _compose_changelog_document(
            ChangelogDocument(
                header=existing.header,
                body=new_body,
                footer=existing.footer,
            )
        ),
        encoding="utf-8",
    )


def run_changelog_pipeline(
    changelog_path: Path,
    repo_root: Path,
    *,
    mode: str = "full",
    release_label: str | None = None,
    from_ref: str | None = None,
    to_ref: str = "HEAD",
    prepend: bool = True,
    run_cliff: bool = True,
    cliff_path: Path | None = None,
    skip_polish: bool = False,
    prompt_path: Path | None = None,
) -> None:
    """Run full or per-tag changelog pipeline.

    - changelog_path: Path to the changelog file (must exist after git-cliff if run_cliff).
    - repo_root: Git repo root for git log and git-cliff cwd. Used for .env and config/ prompt override.
    - mode: "full" for legacy whole-file regeneration, "migrate" for initial per-tag document,
      or "deploy-section" to add one section from a git range.
    - release_label: Required for "migrate" and "deploy-section".
    - from_ref/to_ref: Git refs used to build deploy-section range (`from_ref..to_ref`).
    - prepend: If True, insert the new deploy section before older tagged sections.
    - run_cliff: If True and cliff.toml exists, run git-cliff (cliff.toml must set output to changelog_path).
    - cliff_path: Path to cliff.toml (default repo_root/cliff.toml).
    - skip_polish: If True, skip polish step (otherwise uses TOCIFY_BACKEND as for triage).
    - prompt_path: Override path to changelog_consistency_prompt.md (default repo_root/config/).
    """
    valid_modes = {"full", "migrate", "deploy-section"}
    if mode not in valid_modes:
        raise ValueError(f"Unsupported changelog mode: {mode}")
    if not changelog_path.exists() and not run_cliff:
        raise FileNotFoundError(f"Changelog file not found: {changelog_path}")
    resolved_cliff = (cliff_path or repo_root / "cliff.toml").resolve()
    if mode in {"migrate", "deploy-section"} and not release_label:
        raise ValueError("release_label is required for migrate and deploy-section modes")
    if mode == "migrate":
        if not resolved_cliff.is_file():
            raise FileNotFoundError(f"cliff.toml not found: {resolved_cliff}")
        _write_migrated_changelog(
            changelog_path,
            repo_root,
            resolved_cliff,
            release_label=release_label or "",
            prompt_path=prompt_path,
            skip_polish=skip_polish,
        )
        return
    if mode == "deploy-section":
        if not changelog_path.exists():
            raise FileNotFoundError(f"Changelog file not found: {changelog_path}")
        if not resolved_cliff.is_file():
            raise FileNotFoundError(f"cliff.toml not found: {resolved_cliff}")
        revision_range = f"{from_ref}..{to_ref}" if from_ref else to_ref
        template = _split_changelog_document(changelog_path.read_text(encoding="utf-8"))
        section = _prepare_release_section(
            release_label=release_label or "",
            repo_root=repo_root,
            cliff_path=resolved_cliff,
            prompt_path=prompt_path,
            skip_polish=skip_polish,
            document_template=template,
            revision_range=revision_range,
        )
        _insert_release_section(changelog_path, section, prepend=prepend)
        return
    if run_cliff and resolved_cliff.is_file():
        if not changelog_path.exists():
            # git-cliff will create it; ensure parent exists
            changelog_path.parent.mkdir(parents=True, exist_ok=True)
        changelog_path.write_text(_run_git_cliff(repo_root, resolved_cliff), encoding="utf-8")
        if not changelog_path.exists():
            raise FileNotFoundError(
                f"git-cliff did not produce {changelog_path}; set output in cliff.toml to this path"
            )
    _dedupe_changelog(changelog_path)
    _add_changelog_dates(changelog_path, repo_root)
    _filter_changelog(changelog_path)
    if not skip_polish:
        _run_polish(changelog_path, repo_root, prompt_path)
